USE EMSRecords;
GO

DROP TABLE IF EXISTS er.Raw_EMS_Runs;
GO

CREATE TABLE er.Raw_EMS_Runs (
    INCIDENT_DT                    NVARCHAR(50)  NULL,
    INCIDENT_COUNTY                NVARCHAR(254) NULL,
    CHIEF_COMPLAINT_DISPATCH       NVARCHAR(254) NULL,
    CHIEF_COMPLAINT_ANATOMIC_LOC   NVARCHAR(254) NULL,
    PRIMARY_SYMPTOM                NVARCHAR(254) NULL,
    PROVIDER_IMPRESSION_PRIMARY    NVARCHAR(254) NULL,
    DISPOSITION_ED                 NVARCHAR(254) NULL,
    DISPOSITION_HOSPITAL           NVARCHAR(254) NULL,
    INJURY_FLG                     NVARCHAR(10)  NULL,
    NALOXONE_GIVEN_FLG             NVARCHAR(10)  NULL,
    MEDICATION_GIVEN_OTHER_FLG     NVARCHAR(10)  NULL,
    DESTINATION_TYPE               NVARCHAR(254) NULL,
    PROVIDER_TYPE_STRUCTURE        NVARCHAR(254) NULL,
    PROVIDER_TYPE_SERVICE          NVARCHAR(254) NULL,
    PROVIDER_TYPE_SERVICE_LEVEL    NVARCHAR(254) NULL,
    PROVIDER_TO_SCENE_MINS         NVARCHAR(50)  NULL,
    PROVIDER_TO_DESTINATION_MINS   NVARCHAR(50)  NULL,
    UNIT_NOTIFIED_BY_DISPATCH_DT   NVARCHAR(50)  NULL,
    UNIT_ARRIVED_ON_SCENE_DT       NVARCHAR(50)  NULL,
    UNIT_ARRIVED_TO_PATIENT_DT     NVARCHAR(50)  NULL,
    UNIT_LEFT_SCENE_DT             NVARCHAR(50)  NULL,
    PATIENT_ARRIVED_DESTINATION_DT NVARCHAR(50)  NULL,

    RAW_LOADED_AT                  DATETIME2(0) NOT NULL
        CONSTRAINT DF_Raw_EMS_Runs_RawLoadedAt DEFAULT SYSUTCDATETIME()
);
GO
